[package]
name = "amdgpu-simple-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "*"
num-traits = "0.2"
num-derive = "0.4"
num-bigint = "0.4"
either = "*"
